// Generated by CoffeeScript 1.6.1
(function() {
  var options, refreshErrorCounter,
    _this = this;

  refreshErrorCounter = function() {
    return $('#errorCount').html(window.errorLogger.logger.errorList.length);
  };

  options = {
    logger: 'debug',
    onErrorFn: refreshErrorCounter,
    afterSendFn: refreshErrorCounter,
    sendOnDomReady: true,
    sendDelay: 2000,
    debugLoggerOptions: {
      el: '#onErrors',
      displayEach: false
    }
  };

  window.errorLogger = new $.errorLogger(options);

  $('#version').html(window.errorLogger.version);

  $('#throwError').click(function(e) {
    e.preventDefault();
    return $.browser.version;
  });

  $('#refresh').click(function(e) {
    e.preventDefault();
    return document.location.reload(true);
  });

}).call(this);
